ARG from_tag="fermium"
FROM node:${from_tag}

LABEL author="casaper (github.com/casaper)"
LABEL description="Node LTS Fermium with preinstalled express fs path for running server.js"

RUN npm -g install express@4.17.1 --unsafe-perm

EXPOSE 4200

