FROM node:erbium

LABEL author="casaper (github.com/casaper)"
LABEL name="dist serve"

RUN /usr/local/bin/npm install -g fs path express

EXPOSE 4200

CMD ["sh", "-c", "/usr/local/bin/node http-server.js"]
